### ISSUE TITLE
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

### ISSUE THREAD

**Issue by janv8000** [difelice/ejs-loader#19]
When using `ejs-loader` I get the following warning:

> loaderUtils.parseQuery() received a non-string value which can be problematic, see #https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Stacktrace when setting `process.traceDeprecation = true`:
> DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (node_modules\ejs-loader\node_modules\loader-utils\index.js:78:3)
    at Object.module.exports (node_modules\ejs-loader\index.js:6:27)
    at LOADER_EXECUTION (node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:15)
    at node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:69:9
    at node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)                                                                                                                             Hash: ee67b5e6804e7d7cc798
Version: webpack 2.3.2`

Versions:
ejs-loader@^0.3.0:
  version "0.3.0"

loader-utils@^0.2.15, loader-utils@^0.2.16, loader-utils@^0.2.7:
  version "0.2.17"

**Comment by piotrd** [comment]
It seems like PR https://github.com/okonet/ejs-loader/pull/23 is an attempt to address that warning. However it still needs some work.

**Comment by AtofStryker** [comment]
Fixed in version `4.1` via 814bcc53bb6c4055fc966b44011b24f57f659de4
